<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
?>

<template x-if="searchResult.type == 'product_attribute'">
    <a class="w-full block p-2" :href="searchResult.url" :title="searchResult.title">
        <span class="text-sm" x-text="searchResult.title"></span>
        <span class="text-xs uppercase text-gray-500" x-text="searchResult.attribute_label" style="vertical-align: super;"></span>
    </a>
</template>

<script>
    function renderEsAutocompleteTitleAttribute(data)
    {
        data = data.filter(function(item) {
            return item.type === 'product_attribute';
        }).map(function(item) {
            return item['attribute_label']
        }).reduce(function(prev, item) {
            if (item in prev) {
                prev[item]++;
            } else {
                prev[item] = 1;
            }
            return prev;
        }, {});

        data = Object.entries(data).sort(function(item1, item2) {
            return item2[1] - item1[1]
        }).map(function(item) {return item[0]});

        if (data.length > 2) {
            data = data.slice(0, 2);
            data.push('...');
        }

        return data.join(', ');
    }
</script>
