<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
?>

<template x-if="searchResult.type == 'product'">
    <a class="w-full block" :href="searchResult.url" :title="searchResult.title">
        <div class="grid grid-cols-4 gap-4 p-3">
            <div>
                <img :src="searchResult.image" class="inline-block" />
            </div>
            <div class="col-span-3">
                <span class="text-sm" x-text="searchResult.title"></span>
                <span class="text-sm font-bold" x-html="searchResult.price"></span>
            </div>
        </div>
    </a>
</template>
