<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);
?>

<template x-if="searchResult.type == 'cms_page'">
    <a class="w-full block p-2" :href="searchResult.url" :title="searchResult.title">
        <span class="text-sm" x-text="searchResult.title"></span>
    </a>
</template>
